version: '3.9'

services:
  load_balancer:
    container_name: load_balancer
    depends_on:
      - web_service
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

  web_service:
    container_name: web_service
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
    build:
      context: .
      dockerfile: Dockerfile1
    healthcheck:
      interval: 10s
      retries: 3
      test: ["CMD", "curl", "-f", "http://localhost:5000"]
      timeout: 5s
    ports:
      - "${WEB1_PORT}:5000"
    volumes:
      - ./web-service/config.txt:/app/config.txt



